# Analyzing the dataset of used Cars from eBay Kleinanzeigen

# 1.

In [431]:
import pandas as pd
import numpy as np

In [432]:
autos = pd.read_csv("autos.csv", encoding = "Windows-1252")

In [433]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

# 2.

In [434]:
autos.columns = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_PS', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen']

In [435]:
all_vehicle_type = autos["vehicle_type"].value_counts()
print(all_vehicle_type)

limousine     12859
kleinwagen    10822
kombi          9127
bus            4093
cabrio         3061
coupe          2537
suv            1986
andere          420
Name: vehicle_type, dtype: int64

Limousine has the most seller

In [436]:
print(autos.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
date_crawled          50000 non-null object
name                  50000 non-null object
seller                50000 non-null object
offer_type            50000 non-null object
price                 50000 non-null object
abtest                50000 non-null object
vehicle_type          44905 non-null object
registration_year     50000 non-null int64
gearbox               47320 non-null object
power_PS              50000 non-null int64
model                 47242 non-null object
odometer              50000 non-null object
registration_month    50000 non-null int64
fuel_type             45518 non-null object
brand                 50000 non-null object
unrepaired_damage     40171 non-null object
ad_created            50000 non-null object
nr_of_pictures        50000 non-null int64
postal_code           50000 non-null int64
last_seen             50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB
None

In [437]:
autos.loc[autos["vehicle_type"].isnull(),:]

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_PS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
46,2016-03-31 10:53:28,BMW_mit__Lpg,privat,Angebot,"$9,000",control,NaN,2005,automatik,0,NaN,"150,000km",0,NaN,bmw,NaN,2016-03-31 00:00:00,0,12351,2016-04-06 03:44:41
55,2016-03-07 02:47:54,Mercedes_E320_AMG_zu_Tauschen!,privat,Angebot,$1,test,NaN,2017,automatik,224,e_klasse,"125,000km",7,benzin,mercedes_benz,nein,2016-03-06 00:00:00,0,22111,2016-03-08 05:45:44
59,2016-03-17 17:50:54,Mercedes_A_Klasse_W_168__A_140_gruen,privat,Angebot,$700,control,NaN,2016,manuell,0,a_klasse,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-17 00:00:00,0,95356,2016-03-19 17:46:47
64,2016-04-05 07:36:19,Autotransport__Abschlepp_Schlepper,privat,Angebot,$40,test,NaN,2011,NaN,0,5er,"150,000km",5,NaN,bmw,NaN,2016-04-05 00:00:00,0,40591,2016-04-07 12:16:01
65,2016-04-04 19:30:39,Ford_Fiesta_zum_ausschlachten,privat,Angebot,$250,control,NaN,2017,manuell,65,fiesta,"125,000km",9,benzin,ford,NaN,2016-04-04 00:00:00,0,65606,2016-04-05 12:22:12
68,2016-04-03 17:36:59,Mini_cooper_s_clubman_/vollausstattung_/_Navi/...,privat,Angebot,"$10,990",test,NaN,2017,manuell,174,clubman,"100,000km",0,NaN,mini,nein,2016-04-03 00:00:00,0,83135,2016-04-05 17:26:26
71,2016-03-28 19:39:35,Suche_Opel_Astra_F__Corsa_oder_Kadett_E_mit_Re...,privat,Angebot,$0,control,NaN,1990,manuell,0,NaN,"5,000km",0,benzin,opel,NaN,2016-03-28 00:00:00,0,4552,2016-04-07 01:45:48
84,2016-03-27 19:52:54,Renault_twingo,privat,Angebot,$900,control,NaN,2018,NaN,60,twingo,"150,000km",0,NaN,renault,NaN,2016-03-27 00:00:00,0,40589,2016-04-05 18:46:49
87,2016-03-29 23:37:22,Bmw_520_e39_zum_ausschlachten,privat,Angebot,$0,control,NaN,2000,NaN,0,5er,"150,000km",0,NaN,bmw,NaN,2016-03-29 00:00:00,0,82256,2016-04-06 21:18:15
92,2016-03-25 19:47:32,Zu_verkaufen,privat,Angebot,"$1,900",test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,bmw,NaN,2016-03-25 00:00:00,0,72108,2016-04-07 02:16:01
101,2016-03-22 17:51:49,Schnaepchen_in_einem_Jahr_OLDTEIMER_KENNZEICHEN,privat,Angebot,$600,control,NaN,2016,NaN,0,corolla,"150,000km",0,NaN,toyota,NaN,2016-03-22 00:00:00,0,32825,2016-03-22 17:51:49
113,2016-04-03 14:58:29,Golf_4_Anfaenger_auto,privat,Angebot,"$1,200",test,NaN,2017,manuell,75,golf,"150,000km",7,NaN,volkswagen,NaN,2016-04-03 00:00:00,0,97656,2016-04-05 14:15:48
135,2016-03-12 11:00:10,Opel_Meriva_B_Panoramadach__Sitz__und_Lenkradh...,privat,Angebot,"$8,500",control,NaN,2016,manuell,81,meriva,"90,000km",8,diesel,opel,NaN,2016-03-12 00:00:00,0,48147,2016-03-22 14:49:31
147,2016-03-15 14:52:55,VW_Polo_Ersatzteilspender,privat,Angebot,$600,control,NaN,2000,manuell,60,polo,"125,000km",6,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,18311,2016-03-17 09:44:18
164,2016-03-13 20:39:16,Opel_Meriva__nur_76000_Km__unfallfrei__scheckh...,privat,Angebot,"$4,800",control,NaN,2018,manuell,0,meriva,"80,000km",4,benzin,opel,nein,2016-03-13 00:00:00,0,37627,2016-04-04 16:48:02
167,2016-04-02 19:43:45,Suche_VW_Multivan_Innenausstattung_Set_oder_TE...,privat,Angebot,$0,control,NaN,2011,NaN,0,transporter,"5,000km",0,NaN,volkswagen,NaN,2016-04-02 00:00:00,0,64739,2016-04-06 19:45:08
180,2016-03-19 10:50:25,Zu_verkaufen,privat,Angebot,$0,test,NaN,2016,manuell,98,3_reihe,"150,000km",12,benzin,mazda,ja,2016-03-19 00:00:00,0,30966,2016-03-24 03:17:21
196,2016-03-22 17:54:07,Bmw_316i_lpg_coupe___Tausch_moeglich_,privat,Angebot,"$1,950",control,NaN,1996,manuell,102,NaN,"150,000km",6,NaN,bmw,nein,2016-03-22 00:00:00,0,48268,2016-03-25 10:17:25
197,2016-04-05 10:36:24,VW_Polo_9N_an_Bastler,privat,Angebot,$888,control,NaN,2017,manuell,64,polo,"20,000km",7,NaN,volkswagen,ja,2016-04-05 00:00:00,0,58566,2016-04-07 13:16:13
203,2016-03-29 21:47:01,BMW_316i_Touring,privat,Angebot,$750,test,NaN,2000,manuell,102,3er,"150,000km",8,NaN,bmw,NaN,2016-03-29 00:00:00,0,27628,2016-04-06 08:17:48
227,2016-04-04 17:54:21,Als_Bastler_Fahrzeug,privat,Angebot,$300,test,NaN,2016,NaN,0,seicento,"125,000km",0,benzin,fiat,NaN,2016-04-04 00:00:00,0,25924,2016-04-06 19:48:31
234,2016-03-05 16:56:22,Fiat_Punto_Sport,privat,Angebot,$0,control,NaN,2016,NaN,0,punto,"150,000km",0,NaN,fiat,NaN,2016-03-05 00:00:00,0,44789,2016-03-17 22:47:09
253,2016-03-27 13:25:18,Ford_mondeo_Gas_anlage_mit_TÃœV_04.2017,privat,Angebot,"$2,250",test,NaN,2017,manuell,0,mondeo,"150,000km",8,benzin,ford,nein,2016-03-27 00:00:00,0,56575,2016-04-05 15:18:34
256,2016-04-03 20:50:38,Passat_1.9TDI_4Motion_Highline,privat,Angebot,"$4,250",test,NaN,2016,manuell,131,passat,"150,000km",11,NaN,volkswagen,NaN,2016-04-03 00:00:00,0,31224,2016-04-03 20:50:38
259,2016-04-03 23:49:58,guenstiges_Auto_/_auch_defekt,privat,Angebot,$0,control,NaN,2000,NaN,0,NaN,"5,000km",6,NaN,sonstige_autos,NaN,2016-04-03 00:00:00,0,89269,2016-04-06 07:16:22
276,2016-03-09 16:58:42,Peugeot_106_1_4_55kw_Nuer_heute!!!!!!,privat,Angebot,$300,test,NaN,2000,NaN,0,NaN,"150,000km",3,benzin,peugeot,NaN,2016-03-09 00:00:00,0,65479,2016-03-09 18:25:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49689,2016-03-14 15:44:53,VW_GOLF_V_1.9,privat,Angebot,"$4,700",control,NaN,2017,manuell,105,NaN,"150,000km",0,diesel,volkswagen,NaN,2016-03-14 00:00:00,0,22459,2016-03-16 05:45:48
49696,2016-03-08 13:36:21,Audi_A3_1_6_Attraction_mit_TÃœV_10/17,privat,Angebot,"$1,250",control,NaN,2017,manuell,101,a3,"150,000km",8,benzin,audi,nein,2016-03-08 00:00:00,0,26624,2016-03-08 21:17:30
49698,2016-03-13 17:48:17,opel_vectra_b,privat,Angebot,$120,control,NaN,2000,NaN,0,vectra,"150,000km",0,NaN,opel,NaN,2016-03-13 00:00:00,0,9366,2016-03-20 14:47:13
49713,2016-03-22 08:51:10,Toyota_Carina_1600_GL_TA60,privat,Angebot,"$1,500",control,NaN,1985,manuell,70,andere,"150,000km",4,benzin,toyota,NaN,2016-03-22 00:00:00,0,94032,2016-04-03 18:46:52
49715,2016-03-10 22:54:49,a4_b5_1.8t,privat,Angebot,"$1,199",control,NaN,2000,manuell,150,a4,"150,000km",0,NaN,audi,NaN,2016-03-10 00:00:00,0,72108,2016-03-11 18:49:27
49717,2016-03-08 16:50:11,Mazda_323C,privat,Angebot,$270,test,NaN,2000,manuell,88,3_reihe,"150,000km",11,benzin,mazda,NaN,2016-03-08 00:00:00,0,83301,2016-04-07 03:15:30
49722,2016-03-29 10:37:17,fghgfhfghfgh,privat,Angebot,$200,control,NaN,1960,NaN,0,145,"5,000km",0,NaN,alfa_romeo,NaN,2016-03-29 00:00:00,0,24960,2016-03-29 11:39:37
49725,2016-03-26 12:58:05,VW_Passat_2.8l_V6_Syncro_AHK,privat,Angebot,$999,control,NaN,2016,automatik,193,passat,"150,000km",0,NaN,volkswagen,ja,2016-03-26 00:00:00,0,82343,2016-03-26 13:42:13
49728,2016-03-25 16:00:11,Ford_Focus_1.4_16V_Bastlerauto,privat,Angebot,$1,test,NaN,2016,manuell,0,focus,"150,000km",0,benzin,ford,ja,2016-03-25 00:00:00,0,34587,2016-03-25 16:40:21
49731,2016-03-28 13:40:31,Renault_MEGANE_1.6_16V__neu_ZANHRIEMEN_TOP_ZUS...,privat,Angebot,"$1,700",test,NaN,2017,manuell,0,megane,"150,000km",7,NaN,renault,nein,2016-03-28 00:00:00,0,34123,2016-03-31 21:44:52
49739,2016-03-17 15:47:34,Reparaturfaelligen_twingo,privat,Angebot,$0,test,NaN,2016,manuell,58,twingo,"150,000km",0,benzin,renault,nein,2016-03-17 00:00:00,0,27412,2016-03-17 15:47:34
49750,2016-03-29 22:37:59,Volkswagen_Polo_6n,privat,Angebot,$220,test,NaN,2016,NaN,60,NaN,"150,000km",0,NaN,volkswagen,ja,2016-03-29 00:00:00,0,67433,2016-04-02 12:47:26
49770,2016-03-15 12:54:26,VW_Polo_6n_Tuev_Neu!__1.6_75PS,privat,Angebot,$999,control,NaN,2018,manuell,75,polo,"150,000km",12,benzin,volkswagen,nein,2016-03-15 00:00:00,0,24321,2016-04-06 02:16:02
49796,2016-03-09 09:38:38,Opel_corsa_1.4_zu_verkaufen,privat,Angebot,"$4,500",test,NaN,2017,manuell,90,corsa,"70,000km",7,benzin,opel,nein,2016-03-09 00:00:00,0,88433,2016-03-17 20:45:08
49819,2016-03-26 09:53:05,Audi_A3_1_8__Klima__5_Tuerig__Bremsen_neu__Alu...,privat,Angebot,"$2,995",control,NaN,2000,manuell,125,a3,"150,000km",8,benzin,audi,nein,2016-03-26 00:00:00,0,92242,2016-04-05 21:17:23
49841,2016-03-11 15:37:02,Passat_abzugeben.,privat,Angebot,$600,test,NaN,2017,manuell,101,passat,"150,000km",7,NaN,volkswagen,NaN,2016-03-11 00:00:00,0,53804,2016-03-11 16:41:14
49844,2016-03-26 19:43:51,Fahrzeug_Ankauf!!!!,privat,Angebot,"$22,222",control,NaN,2005,NaN,0,NaN,"5,000km",0,NaN,opel,NaN,2016-03-26 00:00:00,0,72160,2016-03-26 19:43:51
49845,2016-03-21 00:50:15,Schlachte_VW_Sharan_vr6_Automatik___no_GTI_16V...,privat,Angebot,$1,test,NaN,2000,automatik,174,sharan,"5,000km",6,benzin,volkswagen,nein,2016-03-20 00:00:00,0,14621,2016-04-05 21:16:16
49852,2016-04-01 04:02:25,TOP__Golf_3_1.8l,privat,Angebot,"$1,450",control,NaN,2016,NaN,75,golf,"150,000km",7,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,67661,2016-04-05 03:17:29
49876,2016-03-22 17:57:24,Audi_a5_3.0_tdi_s_line,privat,Angebot,"$14,700",control,NaN,2016,manuell,0,NaN,"150,000km",10,diesel,audi,NaN,2016-03-22 00:00:00,0,44227,2016-03-22 18:40:53
49880,2016-03-30 08:52:57,E39_528i_an_Bastler,privat,Angebot,$0,control,NaN,2017,manuell,193,5er,"150,000km",4,NaN,bmw,ja,2016-03-30 00:00:00,0,65468,2016-04-07 01:15:27
49910,2016-04-03 21:39:15,Schoener_fast_neuer_Opel_Mokka_in_Zell_Mosel_m...,privat,Angebot,"$22,200",test,NaN,9000,automatik,140,andere,"10,000km",3,benzin,opel,NaN,2016-04-03 00:00:00,0,56856,2016-04-05 22:18:26
49919,2016-03-10 09:49:43,Fiat_Punto,privat,Angebot,$180,test,NaN,2016,manuell,86,punto,"150,000km",8,NaN,fiat,ja,2016-03-10 00:00:00,0,59558,2016-03-10 10:39:58
49926,2016-03-13 00:36:56,Vw_golf_cabrio,privat,Angebot,$850,control,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,volkswagen,NaN,2016-03-12 00:00:00,0,53227,2016-03-15 17:17:49
49935,2016-04-01 21:48:20,Mercedes_A_klasse_angemeldet_mit_Tuef_und_Auto...,privat,Angebot,$800,test,NaN,2017,automatik,101,a_klasse,"150,000km",9,NaN,mercedes_benz,nein,2016-04-01 00:00:00,0,39108,2016-04-01 21:48:20
49938,2016-03-28 18:45:06,Mercedes_Benz_A_160_Avantgarde,privat,Angebot,"$2,300",control,NaN,2016,automatik,102,a_klasse,"150,000km",6,benzin,mercedes_benz,nein,2016-03-28 00:00:00,0,13507,2016-04-07 00:44:35
49943,2016-03-16 20:46:08,Opel_astra,privat,Angebot,$0,control,NaN,2016,manuell,101,astra,"150,000km",8,benzin,opel,NaN,2016-03-16 00:00:00,0,89134,2016-03-17 19:44:20
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19

In [438]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_PS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [439]:
autos.columns

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_PS', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

Change from camel case to snake case since python use snake case

# 3.

In [440]:
autos.describe(include = "all")

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_PS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-04-02 11:37:04,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

CANDIDATES FOR DROPPING

In [441]:
autos["seller"].value_counts()

privat        49999
gewerblich        1
Name: seller, dtype: int64

In [442]:
autos["offer_type"].value_counts()

Angebot    49999
Gesuch         1
Name: offer_type, dtype: int64

In [443]:
autos["nr_of_pictures"].value_counts()

0    50000
Name: nr_of_pictures, dtype: int64

END

Converting price and odometer to int dtype
Changing the column name with the unit of price and odometer

In [444]:
autos["price"] = (autos["price"]
                  .str.replace("$","")
                  .str.replace(",","")
                  .astype(int))

In [445]:
print(autos["price"].head())

0    5000
1    8500
2    8990
3    4350
4    1350
Name: price, dtype: int64

In [446]:
autos["odometer"] = (autos["odometer"]
                  .str.replace("km","")
                  .str.replace(",","")
                  .astype(int))

In [447]:
#This are string values, need to convert to int
price_odometer = autos[["price","odometer"]]
print(price_odometer.head())

   price  odometer
0   5000    150000
1   8500    150000
2   8990     70000
3   4350     70000
4   1350    150000

In [448]:
autos.columns = ['date_crawled', 'name', 'seller', 'offer_type', 'price_$', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_PS', 'model',
       'odometer_km', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen']

# 4.
Finding ang outlier

In [449]:
print(autos["price_$"].unique().shape)
print(autos["price_$"].describe())

(2357,)
count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price_$, dtype: float64

Might be an outlier since the price is too large and i cant find the model of the car

In [450]:
autos[(autos["price_$"] == autos["price_$"].max())]

,date_crawled,name,seller,offer_type,price_$,abtest,vehicle_type,registration_year,gearbox,power_PS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
39705,2016-03-22 14:58:27,Tausch_gegen_gleichwertiges,privat,Angebot,99999999,control,limousine,1999,automatik,224,s_klasse,150000,9,benzin,mercedes_benz,NaN,2016-03-22 00:00:00,0,73525,2016-04-06 05:15:30

There are a lot of cars with no price

In [451]:
autos[(autos["price_$"] == 0)]

,date_crawled,name,seller,offer_type,price_$,abtest,vehicle_type,registration_year,gearbox,power_PS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
71,2016-03-28 19:39:35,Suche_Opel_Astra_F__Corsa_oder_Kadett_E_mit_Re...,privat,Angebot,0,control,NaN,1990,manuell,0,NaN,5000,0,benzin,opel,NaN,2016-03-28 00:00:00,0,4552,2016-04-07 01:45:48
80,2016-03-09 15:57:57,Nissan_Primera_Hatchback_1_6_16v_73_Kw___99Ps_...,privat,Angebot,0,control,coupe,1999,manuell,99,primera,150000,3,benzin,nissan,ja,2016-03-09 00:00:00,0,66903,2016-03-09 16:43:50
87,2016-03-29 23:37:22,Bmw_520_e39_zum_ausschlachten,privat,Angebot,0,control,NaN,2000,NaN,0,5er,150000,0,NaN,bmw,NaN,2016-03-29 00:00:00,0,82256,2016-04-06 21:18:15
99,2016-04-05 09:48:54,Peugeot_207_CC___Cabrio_Bj_2011,privat,Angebot,0,control,cabrio,2011,manuell,0,2_reihe,60000,7,diesel,peugeot,nein,2016-04-05 00:00:00,0,99735,2016-04-07 12:17:34
118,2016-03-12 05:03:00,VW_Sharan_V6_204_PS_Karosse_Rohkarosse_mit_Pap...,privat,Angebot,0,control,bus,2001,manuell,204,sharan,150000,7,benzin,volkswagen,ja,2016-03-12 00:00:00,0,15370,2016-03-12 21:44:23
146,2016-03-22 23:59:28,Ford_Fiesta_rot,privat,Angebot,0,test,kleinwagen,1996,manuell,75,fiesta,20000,8,benzin,ford,NaN,2016-03-22 00:00:00,0,63069,2016-04-01 20:16:38
167,2016-04-02 19:43:45,Suche_VW_Multivan_Innenausstattung_Set_oder_TE...,privat,Angebot,0,control,NaN,2011,NaN,0,transporter,5000,0,NaN,volkswagen,NaN,2016-04-02 00:00:00,0,64739,2016-04-06 19:45:08
180,2016-03-19 10:50:25,Zu_verkaufen,privat,Angebot,0,test,NaN,2016,manuell,98,3_reihe,150000,12,benzin,mazda,ja,2016-03-19 00:00:00,0,30966,2016-03-24 03:17:21
226,2016-03-25 23:52:12,Porsche_911_S_Targa__67er_SWB,privat,Angebot,0,control,cabrio,1967,manuell,160,911,5000,12,benzin,porsche,nein,2016-03-25 00:00:00,0,44575,2016-04-05 14:46:39
234,2016-03-05 16:56:22,Fiat_Punto_Sport,privat,Angebot,0,control,NaN,2016,NaN,0,punto,150000,0,NaN,fiat,NaN,2016-03-05 00:00:00,0,44789,2016-03-17 22:47:09
248,2016-03-08 22:57:53,VW_Passat_zu_verkaufen,privat,Angebot,0,test,kombi,1998,manuell,0,passat,150000,10,benzin,volkswagen,ja,2016-03-08 00:00:00,0,34369,2016-03-29 16:16:18
259,2016-04-03 23:49:58,guenstiges_Auto_/_auch_defekt,privat,Angebot,0,control,NaN,2000,NaN,0,NaN,5000,6,NaN,sonstige_autos,NaN,2016-04-03 00:00:00,0,89269,2016-04-06 07:16:22
301,2016-03-08 20:37:59,Kaufe_alle_Autos_bietet_an,privat,Angebot,0,control,NaN,1990,NaN,0,NaN,5000,0,NaN,sonstige_autos,NaN,2016-03-08 00:00:00,0,13589,2016-04-05 18:44:43
323,2016-03-15 16:54:59,W220_Unfallfahrzeug,privat,Angebot,0,control,limousine,2001,automatik,224,s_klasse,150000,8,NaN,mercedes_benz,NaN,2016-03-15 00:00:00,0,45475,2016-04-06 12:44:20
327,2016-04-03 13:49:21,BMW_Cabrio_318i_/_BMW_318_tds_Touring,privat,Angebot,0,control,NaN,2016,manuell,90,3er,150000,2,diesel,bmw,NaN,2016-04-03 00:00:00,0,39112,2016-04-05 12:46:23
347,2016-04-02 11:48:02,Volvo_TP21__Sugga,privat,Angebot,0,test,suv,1956,NaN,0,andere,100000,0,NaN,volvo,NaN,2016-04-02 00:00:00,0,34414,2016-04-04 09:15:24
366,2016-03-21 20:36:25,Ford_Escort_Express_75__LKW_Zulussung___Diesel...,privat,Angebot,0,control,NaN,2000,NaN,0,andere,90000,0,diesel,ford,NaN,2016-03-21 00:00:00,0,3130,2016-03-28 19:16:45
389,2016-03-08 11:38:52,Vw_polo_classic,privat,Angebot,0,control,limousine,1999,manuell,75,NaN,150000,0,NaN,volkswagen,NaN,2016-03-08 00:00:00,0,14476,2016-03-14 09:16:30
418,2016-03-29 14:43:24,Fiat_SCUDO_8_Sitzer_Bus__Diesel_JTD__80_KW,privat,Angebot,0,test,bus,2003,manuell,80,andere,5000,5,diesel,fiat,nein,2016-03-29 00:00:00,0,35315,2016-04-05 23:47:14
427,2016-03-12 11:44:47,TOP_ZUSTAND_GrunePlakette_Euro4!!!,privat,Angebot,0,test,bus,2005,manuell,101,vivaro,80000,8,diesel,opel,nein,2016-03-12 00:00:00,0,93173,2016-03-12 11:44:47
430,2016-03-18 23:52:40,Winterraeder_FORD,privat,Angebot,0,test,NaN,2007,NaN,0,focus,5000,0,NaN,ford,NaN,2016-03-18 00:00:00,0,40549,2016-03-19 06:47:06
449,2016-04-03 20:59:59,Tausche_gegen_ein_smart.,privat,Angebot,0,test,limousine,2001,manuell,120,golf,150000,8,benzin,volkswagen,nein,2016-04-03 00:00:00,0,60439,2016-04-04 10:31:06
487,2016-03-14 21:41:36,MAG_MICH_KEINER_HABEN_Opel_Omega_B_Caravan_2.0...,privat,Angebot,0,test,kombi,1998,manuell,136,omega,150000,8,benzin,opel,ja,2016-03-14 00:00:00,0,59320,2016-03-17 11:48:08
502,2016-03-25 23:55:24,C32_AMG_C55_C43_w203,privat,Angebot,0,control,kombi,2001,NaN,354,c_klasse,150000,0,benzin,mercedes_benz,NaN,2016-03-25 00:00:00,0,79112,2016-03-26 08:40:35
519,2016-03-28 08:53:58,Verkaufe/Tausche_Seat_Inca__VW_Caddy__aus_2002...,privat,Angebot,0,test,andere,2002,manuell,64,andere,150000,2,diesel,seat,nein,2016-03-28 00:00:00,0,12627,2016-03-28 10:41:01
565,2016-03-20 20:49:36,Tausche_Audi_S3_8p_gegen_Golf_VI_Gti_mit_xenon,privat,Angebot,0,test,NaN,2016,manuell,330,NaN,150000,9,NaN,audi,nein,2016-03-20 00:00:00,0,97488,2016-03-22 00:44:53
593,2016-04-01 21:44:15,CLK_200__BRABUS_Optik,privat,Angebot,0,test,coupe,1998,manuell,136,clk,150000,1,benzin,mercedes_benz,NaN,2016-04-01 00:00:00,0,49191,2016-04-05 19:16:21
660,2016-03-29 21:44:40,Opel_Corsa_B,privat,Angebot,0,test,kleinwagen,1998,manuell,54,corsa,125000,11,benzin,opel,ja,2016-03-29 00:00:00,0,24214,2016-04-06 07:46:43
661,2016-03-18 22:49:48,Renault_Megane_Scenic_1.6_Tuev_12/17,privat,Angebot,0,test,bus,1999,manuell,0,megane,150000,8,benzin,renault,NaN,2016-03-18 00:00:00,0,66346,2016-03-29 16:47:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48882,2016-03-14 23:58:47,SUCHE_AUTO,privat,Angebot,0,control,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,97753,2016-03-30 23:47:43
48889,2016-04-01 10:50:52,Audi_A4_____TueV_09.2016,privat,Angebot,0,control,limousine,1995,manuell,101,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,86869,2016-04-07 07:46:02
48891,2016-03-20 22:50:14,MB_E_220_CDI__TAUSCHEN_nur_SUV/GELÃ„NDEWAGEN,privat,Angebot,0,test,kombi,2001,automatik,143,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-20 00:00:00,0,38442,2016-03-24 18:16:00
48982,2016-03-08 12:48:33,Bmw_525D_Sport_Pro..Navi,privat,Angebot,0,test,limousine,2010,automatik,204,5er,150000,10,diesel,bmw,NaN,2016-03-08 00:00:00,0,47805,2016-03-11 16:15:39
48985,2016-03-27 08:55:25,Stockcar_Autos_Peugeot,privat,Angebot,0,test,NaN,2007,NaN,60,NaN,5000,0,NaN,peugeot,NaN,2016-03-27 00:00:00,0,17153,2016-04-07 05:17:18
49043,2016-03-07 11:48:55,Opel_Vectra_B_Caravan,privat,Angebot,0,test,kombi,1997,manuell,101,NaN,150000,0,benzin,opel,NaN,2016-03-07 00:00:00,0,48429,2016-03-17 21:20:07
49082,2016-03-13 17:06:58,Passat_35i_b4_in_candy_weiss_original_lack,privat,Angebot,0,test,limousine,1996,manuell,90,NaN,150000,6,NaN,volkswagen,nein,2016-03-13 00:00:00,0,35799,2016-04-04 06:45:30
49254,2016-03-21 10:49:57,Corrado_G60_mit_2e_Motor,privat,Angebot,0,test,NaN,1995,manuell,0,NaN,150000,0,benzin,volkswagen,NaN,2016-03-21 00:00:00,0,53639,2016-03-22 15:18:35
49301,2016-03-20 20:52:40,Golf_3_Variant_Kombi_1.8,privat,Angebot,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,volkswagen,NaN,2016-03-20 00:00:00,0,4924,2016-03-30 15:17:15
49342,2016-03-09 20:47:01,Audi_80_b4_S_Color_und_BMW_318ti_compact_Tausc...,privat,Angebot,0,test,NaN,2017,manuell,90,80,150000,10,benzin,audi,ja,2016-03-09 00:00:00,0,25853,2016-03-11 17:45:36
49350,2016-03-19 23:57:15,Golf_II_Diesel,privat,Angebot,0,control,kleinwagen,1991,manuell,54,golf,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,29664,2016-04-06 03:15:23
49404,2016-04-04 03:03:16,Golf_2_BBS_LEDER_KW,privat,Angebot,0,control,limousine,1989,manuell,90,NaN,150000,3,NaN,volkswagen,nein,2016-04-04 00:00:00,0,52062,2016-04-06 08:45:25
49408,2016-03-30 20:57:06,OPEL_ASTRA,privat,Angebot,0,control,NaN,1995,manuell,60,astra,150000,0,benzin,opel,ja,2016-03-30 00:00:00,0,27711,2016-04-05 11:46:06
49479,2016-04-01 23:55:01,Tausch_mit_frischen_TÃœV,privat,Angebot,0,control,limousine,1995,manuell,101,a4,150000,5,benzin,audi,nein,2016-04-01 00:00:00,0,27753,2016-04-06 05:16:07
49496,2016-03-26 13:55:28,Bmw_e39_520,privat,Angebot,0,control,limousine,1998,manuell,0,NaN,5000,0,NaN,bmw,NaN,2016-03-26 00:00:00,0,26188,2016-03-26 13:55:28
49504,2016-03-13 19:42:57,Meriva_Lpg_1_6_16v,privat,Angebot,0,control,bus,2004,manuell,101,meriva,150000,10,lpg,opel,ja,2016-03-13 00:00:00,0,27432,2016-03-19 13:16:57
49507,2016-03-16 17:38:32,BMW_528i_E39_Schaltgetriebe_Unfall,privat,Angebot,0,control,limousine,1998,manuell,193,5er,150000,0,NaN,bmw,ja,2016-03-16 00:00:00,0,25541,2016-03-30 08:47:38
49525,2016-03-09 17:59:02,Bmw_e36_318_i_Limo_Ringtool_PS_Tuning,privat,Angebot,0,test,NaN,2000,NaN,160,3er,150000,0,NaN,bmw,NaN,2016-03-09 00:00:00,0,66822,2016-03-15 04:45:26
49538,2016-03-14 10:55:27,Golf_3_mit_Tuev_.....PREISWERT!!!!,privat,Angebot,0,control,limousine,1998,manuell,60,golf,150000,0,benzin,volkswagen,nein,2016-03-14 00:00:00,0,15345,2016-03-14 10:55:27
49551,2016-03-16 23:40:18,Golf_IV_an_Bastler_zuverkaufen__reserviert_,privat,Angebot,0,test,NaN,2016,manuell,0,NaN,150000,6,diesel,volkswagen,nein,2016-03-16 00:00:00,0,4275,2016-03-16 23:40:18
49614,2016-03-09 17:49:39,Verkauf_meine__Audi__A3_.Gegen_tauschen_mit_Di...,privat,Angebot,0,test,NaN,2016,manuell,101,a3,150000,0,benzin,audi,nein,2016-03-09 00:00:00,0,47051,2016-03-10 14:15:53
49739,2016-03-17 15:47:34,Reparaturfaelligen_twingo,privat,Angebot,0,test,NaN,2016,manuell,58,twingo,150000,0,benzin,renault,nein,2016-03-17 00:00:00,0,27412,2016-03-17 15:47:34
49755,2016-04-02 13:46:23,Mercedes_Benz_w202_unfaller,privat,Angebot,0,test,limousine,1998,manuell,136,c_klasse,150000,7,benzin,mercedes_benz,NaN,2016-04-02 00:00:00,0,99441,2016-04-02 13:46:23
49793,2016-03-05 14:58:49,verkaufe_BMW_E_39,privat,Angebot,0,control,kombi,2000,automatik,183,5er,150000,1,benzin,bmw,NaN,2016-03-05 00:00:00,0,13125,2016-03-05 18:47:14
49880,2016-03-30 08:52:57,E39_528i_an_Bastler,privat,Angebot,0,control,NaN,2017,manuell,193,5er,150000,4,NaN,bmw,ja,2016-03-30 00:00:00,0,65468,2016-04-07 01:15:27
49884,2016-03-11 13:55:30,Audi_a6_2.5l__Schnaeppchen_nur_heute,privat,Angebot,0,test,kombi,1999,manuell,150,a6,150000,11,diesel,audi,NaN,2016-03-11 00:00:00,0,27711,2016-03-12 03:17:08
49943,2016-03-16 20:46:08,Opel_astra,privat,Angebot,0,control,NaN,2016,manuell,101,astra,150000,8,benzin,opel,NaN,2016-03-16 00:00:00,0,89134,2016-03-17 19:44:20
49960,2016-03-25 22:51:55,Ford_KA_zu_verschenken_***Reserviert***,privat,Angebot,0,control,kleinwagen,1999,manuell,60,ka,150000,6,benzin,ford,NaN,2016-03-25 00:00:00,0,34355,2016-03-25 22:51:55
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,0,control,cabrio,1983,manuell,70,golf,150000,2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53

In [452]:
autos["price_$"]

0         5000
1         8500
2         8990
3         4350
4         1350
5         7900
6          300
7         1990
8          250
9          590
10         999
11         350
12        5299
13        1350
14        3999
15       18900
16         350
17        5500
18         300
19        4150
20        3500
21       41500
22       25450
23        7999
24       48500
25          90
26         777
27           0
28        5250
29        4999
         ...
49970    15800
49971      950
49972     3300
49973     6000
49974        0
49975     9700
49976     5900
49977     5500
49978      900
49979    11000
49980      400
49981     2000
49982     1950
49983      600
49984        0
49985     1000
49986    15900
49987    21990
49988     9550
49989      150
49990    17500
49991      500
49992     4800
49993     1650
49994     5000
49995    24900
49996     1980
49997    13200
49998    22900
49999     1250
Name: price_$, Length: 50000, dtype: int64

In [453]:
autos["price_$"].value_counts().sort_index().head(20)

0     1421
1      156
2        3
3        1
5        2
8        1
9        1
10       7
11       2
12       3
13       2
14       1
15       2
17       3
18       1
20       4
25       5
29       1
30       7
35       1
Name: price_$, dtype: int64

In [454]:
autos["price_$"].value_counts().sort_index().tail(20)

197000      1
198000      1
220000      1
250000      1
259000      1
265000      1
295000      1
299000      1
345000      1
350000      1
999990      1
999999      2
1234566     1
1300000     1
3890000     1
10000000    1
11111111    2
12345678    3
27322222    1
99999999    1
Name: price_$, dtype: int64

In [455]:
autos["price_$"] = autos.loc[autos["price_$"].between(1,350000),"price_$"]

In [456]:
autos["price_$"].describe(include = "all")

count     48565.000000
mean       5888.935591
std        9059.854754
min           1.000000
25%        1200.000000
50%        3000.000000
75%        7490.000000
max      350000.000000
Name: price_$, dtype: float64

REMOVED THE OUTLIER WITH THE VALUE 99999999 AND 0 PRICE. 
ITS SEEMS THAT 99999999 TO BE AN OUTLIER SINCE ITS ON EBAY. AS FOR THE ZERO PRICE. ITS AN ERROR

In [457]:
print(autos["odometer_km"].unique().shape)
print(autos["odometer_km"].describe())

(13,)
count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [458]:
print(autos[(autos["odometer_km"] == autos["odometer_km"].max() )].shape)

(32424, 20)

There are no outliers in the odometer column since the max value is equal to the median and the 75 percentile.

# 5.

In [459]:
autos["date_crawled"].value_counts(normalize = True,dropna=False)

2016-04-02 11:37:04    0.00006
2016-03-10 15:36:24    0.00006
2016-04-04 16:40:33    0.00006
2016-03-25 19:57:10    0.00006
2016-04-02 15:49:30    0.00006
2016-03-30 17:37:35    0.00006
2016-03-19 17:36:18    0.00006
2016-03-29 23:42:13    0.00006
2016-03-09 11:54:38    0.00006
2016-03-05 16:57:05    0.00006
2016-03-08 10:40:35    0.00006
2016-03-12 16:06:22    0.00006
2016-03-21 20:37:19    0.00006
2016-03-11 22:38:16    0.00006
2016-03-30 19:48:02    0.00006
2016-03-22 09:51:06    0.00006
2016-03-21 16:37:21    0.00006
2016-03-14 20:50:02    0.00006
2016-03-23 18:39:34    0.00006
2016-03-27 22:55:05    0.00006
2016-03-16 21:50:53    0.00006
2016-03-23 19:38:20    0.00006
2016-03-11 17:47:44    0.00004
2016-03-11 11:54:09    0.00004
2016-03-20 14:54:13    0.00004
2016-03-08 13:51:58    0.00004
2016-04-04 18:46:47    0.00004
2016-04-03 16:48:45    0.00004
2016-03-28 16:45:41    0.00004
2016-03-31 12:55:26    0.00004
                        ...
2016-03-05 22:52:02    0.00002
2016-03-14 10:45:23    0.00002
2016-03-23 17:00:06    0.00002
2016-03-16 18:50:41    0.00002
2016-03-26 17:40:16    0.00002
2016-03-17 15:49:34    0.00002
2016-03-27 13:51:10    0.00002
2016-03-21 15:49:39    0.00002
2016-04-01 23:47:25    0.00002
2016-04-02 20:45:04    0.00002
2016-04-04 12:52:52    0.00002
2016-03-20 09:32:23    0.00002
2016-03-30 20:42:31    0.00002
2016-03-05 19:50:08    0.00002
2016-04-02 13:42:55    0.00002
2016-03-24 10:41:17    0.00002
2016-03-26 10:54:04    0.00002
2016-03-07 18:46:44    0.00002
2016-03-22 09:56:51    0.00002
2016-03-13 17:47:21    0.00002
2016-03-08 00:57:53    0.00002
2016-03-15 09:48:44    0.00002
2016-03-15 10:43:29    0.00002
2016-03-21 16:00:21    0.00002
2016-03-10 19:38:34    0.00002
2016-04-02 14:51:21    0.00002
2016-03-14 10:54:49    0.00002
2016-03-25 17:51:54    0.00002
2016-04-01 17:49:55    0.00002
2016-04-01 22:48:38    0.00002
Name: date_crawled, Length: 48213, dtype: float64

In [460]:
autos["date_crawled"].describe()

count                   50000
unique                  48213
top       2016-04-02 11:37:04
freq                        3
Name: date_crawled, dtype: object

In [461]:
#autos_copy["date_crawled"]= autos_copy["date_crawled"].str.split("-")

In [462]:
autos["date_crawled"]= (autos["date_crawled"]
                       .str.split()
                     .str[0]
                    )

In [464]:
autos["date_crawled"].value_counts(dropna = False).sort_index()

2016-03-05    1269
2016-03-06     697
2016-03-07    1798
2016-03-08    1665
2016-03-09    1661
2016-03-10    1606
2016-03-11    1624
2016-03-12    1839
2016-03-13     778
2016-03-14    1831
2016-03-15    1699
2016-03-16    1475
2016-03-17    1576
2016-03-18     653
2016-03-19    1745
2016-03-20    1891
2016-03-21    1876
2016-03-22    1647
2016-03-23    1619
2016-03-24    1455
2016-03-25    1587
2016-03-26    1624
2016-03-27    1552
2016-03-28    1742
2016-03-29    1709
2016-03-30    1681
2016-03-31    1596
2016-04-01    1690
2016-04-02    1770
2016-04-03    1934
2016-04-04    1826
2016-04-05     655
2016-04-06     159
2016-04-07      71
Name: date_crawled, dtype: int64

In [463]:
autos["date_crawled"].value_counts()

2016-04-03    1934
2016-03-20    1891
2016-03-21    1876
2016-03-12    1839
2016-03-14    1831
2016-04-04    1826
2016-03-07    1798
2016-04-02    1770
2016-03-19    1745
2016-03-28    1742
2016-03-29    1709
2016-03-15    1699
2016-04-01    1690
2016-03-30    1681
2016-03-08    1665
2016-03-09    1661
2016-03-22    1647
2016-03-26    1624
2016-03-11    1624
2016-03-23    1619
2016-03-10    1606
2016-03-31    1596
2016-03-25    1587
2016-03-17    1576
2016-03-27    1552
2016-03-16    1475
2016-03-24    1455
2016-03-05    1269
2016-03-13     778
2016-03-06     697
2016-04-05     655
2016-03-18     653
2016-04-06     159
2016-04-07      71
Name: date_crawled, dtype: int64

1. 2016-04-03 has the most date_crawled = 1934.
2. 2016-04-07 has the least date_crawled = 71
3. There are no values == 1.
4. We use Series.sort_index() method because Series.value_counts() returns a series of values of each date and date as its index. 
5. We used normalize to scale the column to 0-1 only
6. The first to crawl is in 2016-03-05 which has a value of 1269
7. The last to crawl is in 2016-04-07 which has a value of 71. Also the least date_crawled.

In [465]:
autos["ad_created"]= (autos["ad_created"]
                       .str.split()
                     .str[0]
                    )

In [466]:
autos["ad_created"].value_counts(dropna = False).sort_index()

2015-06-11       1
2015-08-10       1
2015-09-09       1
2015-11-10       1
2015-12-05       1
2015-12-30       1
2016-01-03       1
2016-01-07       1
2016-01-10       2
2016-01-13       1
2016-01-14       1
2016-01-16       1
2016-01-22       1
2016-01-27       3
2016-01-29       1
2016-02-01       1
2016-02-02       2
2016-02-05       2
2016-02-07       1
2016-02-08       1
2016-02-09       2
2016-02-11       1
2016-02-12       3
2016-02-14       2
2016-02-16       1
2016-02-17       1
2016-02-18       2
2016-02-19       3
2016-02-20       2
2016-02-21       3
              ...
2016-03-09    1662
2016-03-10    1593
2016-03-11    1639
2016-03-12    1831
2016-03-13     846
2016-03-14    1761
2016-03-15    1687
2016-03-16    1500
2016-03-17    1560
2016-03-18     686
2016-03-19    1692
2016-03-20    1893
2016-03-21    1886
2016-03-22    1640
2016-03-23    1609
2016-03-24    1454
2016-03-25    1594
2016-03-26    1628
2016-03-27    1545
2016-03-28    1748
2016-03-29    1707
2016-03-30    1672
2016-03-31    1596
2016-04-01    1690
2016-04-02    1754
2016-04-03    1946
2016-04-04    1844
2016-04-05     592
2016-04-06     163
2016-04-07      64
Name: ad_created, Length: 76, dtype: int64

In [467]:
autos["ad_created"].value_counts()

2016-04-03    1946
2016-03-20    1893
2016-03-21    1886
2016-04-04    1844
2016-03-12    1831
2016-03-14    1761
2016-04-02    1754
2016-03-28    1748
2016-03-07    1737
2016-03-29    1707
2016-03-19    1692
2016-04-01    1690
2016-03-15    1687
2016-03-30    1672
2016-03-08    1667
2016-03-09    1662
2016-03-22    1640
2016-03-11    1639
2016-03-26    1628
2016-03-23    1609
2016-03-31    1596
2016-03-25    1594
2016-03-10    1593
2016-03-17    1560
2016-03-27    1545
2016-03-16    1500
2016-03-24    1454
2016-03-05    1152
2016-03-13     846
2016-03-06     756
              ...
2016-02-21       3
2016-02-14       2
2016-02-24       2
2016-02-18       2
2016-02-02       2
2016-02-20       2
2016-02-26       2
2016-02-09       2
2016-01-10       2
2016-02-05       2
2016-01-07       1
2016-01-22       1
2016-02-17       1
2016-02-16       1
2016-02-07       1
2016-01-03       1
2016-02-01       1
2015-08-10       1
2016-02-22       1
2016-01-16       1
2015-11-10       1
2016-02-08       1
2015-06-11       1
2016-02-11       1
2015-09-09       1
2015-12-05       1
2016-01-14       1
2016-01-29       1
2016-01-13       1
2015-12-30       1
Name: ad_created, Length: 76, dtype: int64

1. 2016-04-03 has the most ad created date with a value of 1946.
2. There are a lot of dates which has only one ad was created.
3. 2015-06-11 is the date in which the first ad was created
4. 2016-04-07 is the last date which have 64 ad created.

In [468]:
autos["last_seen"]= (autos["last_seen"]
                    .str.split()
                     .str[0]
                    )

In [469]:
autos["last_seen"].value_counts(normalize = True ,dropna = False).sort_index()

2016-03-05    0.00108
2016-03-06    0.00442
2016-03-07    0.00536
2016-03-08    0.00760
2016-03-09    0.00986
2016-03-10    0.01076
2016-03-11    0.01252
2016-03-12    0.02382
2016-03-13    0.00898
2016-03-14    0.01280
2016-03-15    0.01588
2016-03-16    0.01644
2016-03-17    0.02792
2016-03-18    0.00742
2016-03-19    0.01574
2016-03-20    0.02070
2016-03-21    0.02074
2016-03-22    0.02158
2016-03-23    0.01858
2016-03-24    0.01956
2016-03-25    0.01920
2016-03-26    0.01696
2016-03-27    0.01602
2016-03-28    0.02086
2016-03-29    0.02234
2016-03-30    0.02484
2016-03-31    0.02384
2016-04-01    0.02310
2016-04-02    0.02490
2016-04-03    0.02536
2016-04-04    0.02462
2016-04-05    0.12428
2016-04-06    0.22100
2016-04-07    0.13092
Name: last_seen, dtype: float64

In [470]:
autos["last_seen"].value_counts(dropna = False)

2016-04-06    11050
2016-04-07     6546
2016-04-05     6214
2016-03-17     1396
2016-04-03     1268
2016-04-02     1245
2016-03-30     1242
2016-04-04     1231
2016-03-31     1192
2016-03-12     1191
2016-04-01     1155
2016-03-29     1117
2016-03-22     1079
2016-03-28     1043
2016-03-21     1037
2016-03-20     1035
2016-03-24      978
2016-03-25      960
2016-03-23      929
2016-03-26      848
2016-03-16      822
2016-03-27      801
2016-03-15      794
2016-03-19      787
2016-03-14      640
2016-03-11      626
2016-03-10      538
2016-03-09      493
2016-03-13      449
2016-03-08      380
2016-03-18      371
2016-03-07      268
2016-03-06      221
2016-03-05       54
Name: last_seen, dtype: int64

1. 2016-04-06 has the greatest value in which an ad was seen online = 11050
2. 2016-03-05 has the least value in which an ad was seen online =54

In [471]:
autos["registration_year"].describe()

count    50000.000000
mean      2005.073280
std        105.712813
min       1000.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

The max and min value is an outlier

In [472]:
autos["registration_year"] = autos.loc[(autos["registration_year"]
                                                  .between(autos["registration_year"].min()+900,autos["registration_year"].max()-7899)),"registration_year"]

# 6.

In [473]:
autos["registration_year"].describe()

count    49976.000000
mean      2003.366836
std          7.693943
min       1910.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       2019.000000
Name: registration_year, dtype: float64

I cleaned it by selecting only values between min(which is 1000) + 900 and max(which is 9999) - 7899
    #between 1900 and 2100

In [474]:
autos["registration_year"].value_counts(normalize = True)

2000.0    0.067112
2005.0    0.060329
1999.0    0.060029
2004.0    0.054766
2003.0    0.054566
2006.0    0.054186
2001.0    0.054086
2002.0    0.050684
1998.0    0.049084
2007.0    0.046102
2008.0    0.044641
2009.0    0.041980
1997.0    0.040579
2011.0    0.032696
2010.0    0.031955
2017.0    0.029074
1996.0    0.028894
2012.0    0.026473
2016.0    0.026333
1995.0    0.026273
2013.0    0.016128
2014.0    0.013326
1994.0    0.013206
2018.0    0.009845
1993.0    0.008904
2015.0    0.007984
1990.0    0.007904
1992.0    0.007824
1991.0    0.007123
1989.0    0.003622
            ...
1966.0    0.000440
1975.0    0.000380
1969.0    0.000380
1965.0    0.000340
1964.0    0.000240
1963.0    0.000180
1910.0    0.000180
1959.0    0.000140
1961.0    0.000120
1956.0    0.000100
1962.0    0.000080
1958.0    0.000080
1937.0    0.000080
2019.0    0.000060
1950.0    0.000060
1934.0    0.000040
1941.0    0.000040
1951.0    0.000040
1954.0    0.000040
1955.0    0.000040
1957.0    0.000040
1952.0    0.000020
1953.0    0.000020
1948.0    0.000020
1943.0    0.000020
1939.0    0.000020
1938.0    0.000020
1931.0    0.000020
1929.0    0.000020
1927.0    0.000020
Name: registration_year, Length: 81, dtype: float64

In [422]:
autos["brand"].value_counts()

volkswagen        10687
opel               5461
bmw                5429
mercedes_benz      4734
audi               4283
ford               3479
renault            2404
peugeot            1456
fiat               1308
seat                941
skoda               786
mazda               757
nissan              754
smart               701
citroen             701
toyota              617
sonstige_autos      546
hyundai             488
volvo               457
mini                424
mitsubishi          406
honda               399
kia                 356
alfa_romeo          329
porsche             294
suzuki              293
chevrolet           283
chrysler            181
dacia               129
daihatsu            128
jeep                110
subaru              109
land_rover           99
saab                 80
daewoo               79
trabant              78
jaguar               77
rover                69
lancia               57
lada                 31
Name: brand, dtype: int64

# 7.

## Exploring the brand column

Choosing what brand to aggregate. Because we're computing the mean. And if data is not large enough. Then it wont be reliable

In [476]:
brands = autos["brand"].value_counts(normalize = True)

In [496]:
all_brand = {}
common_brands = brands[brands > 5].index

In [497]:
autos["brand"].value_counts(normalize = True).head()

volkswagen       0.21374
opel             0.10922
bmw              0.10858
mercedes_benz    0.09468
audi             0.08566
Name: brand, dtype: float64

In [498]:
for brand in all_brand_unique:
    brand_mean = autos.loc[(autos["brand"] == brand),"price_$"].mean()
    all_brand[brand] = int(brand_mean)

In [499]:
all_brand

{'audi': 9212,
 'bmw': 8261,
 'ford': 3728,
 'mercedes_benz': 8536,
 'opel': 2944,
 'volkswagen': 5332}

In [501]:
all_brand_mean = pd.Series(all_brand)
print(all_brand_mean)

audi             9212
bmw              8261
ford             3728
mercedes_benz    8536
opel             2944
volkswagen       5332
dtype: int64

In [ ]:
df = pd.DataFrame(all_brand_mean, columns = ["mean_price"])
print()